"""empty message

Revision ID: 9e93dcb87079
Revises: 5eec6356b354
Create Date: 2019-06-27 20:23:24.560609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e93dcb87079'
down_revision = '5eec6356b354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('follower', sa.Integer(), nullable=False),
    sa.Column('followed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower', 'followed')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('following')
    # ### end Alembic commands ###
